#!/usr/bin/env bash
# Generate the secrets the office server needs (ADR-033).
#
#   deploy/keygen.sh >> deploy/env/production.env
#
# ANON_KEY and SERVICE_ROLE_KEY are not random strings: they are JWTs signed with
# JWT_SECRET, because PostgREST and Storage verify them as JWTs. They are built
# here with openssl so the server needs no Node, no npm and no internet access to
# be provisioned.
#
# Run this ONCE. Re-running produces a new JWT_SECRET, which invalidates every
# signed-in session and every key issued from the old one — everybody would have
# to sign in again, and any service still holding an old key would be refused.
set -euo pipefail

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

sign() {           # sign <secret> <payload-json>
  local secret="$1" payload="$2" header data sig
  header=$(printf '%s' '{"alg":"HS256","typ":"JWT"}' | b64url)
  data="${header}.$(printf '%s' "$payload" | b64url)"
  sig=$(printf '%s' "$data" \
    | openssl dgst -sha256 -hmac "$secret" -binary \
    | b64url)
  printf '%s.%s' "$data" "$sig"
}

# 40 hex characters. Long enough that brute force is not a consideration, and
# free of shell metacharacters so it survives every config file it is pasted in.
POSTGRES_PASSWORD=$(openssl rand -hex 20)
JWT_SECRET=$(openssl rand -hex 32)
CRON_SECRET=$(openssl rand -hex 24)
BACKUP_PASSPHRASE=$(openssl rand -hex 24)

IAT=$(date +%s)
# Ten years. These keys identify a deployment rather than a person, and an
# expiry that lands on a random Tuesday in three years is an outage nobody will
# connect to a token when it happens.
EXP=$((IAT + 315360000))

ANON_KEY=$(sign "$JWT_SECRET" "{\"role\":\"anon\",\"iss\":\"supabase\",\"iat\":${IAT},\"exp\":${EXP}}")
SERVICE_ROLE_KEY=$(sign "$JWT_SECRET" "{\"role\":\"service_role\",\"iss\":\"supabase\",\"iat\":${IAT},\"exp\":${EXP}}")

cat <<OUT

# --- generated by deploy/keygen.sh on $(date -u '+%Y-%m-%d %H:%M UTC') ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
CRON_SECRET=${CRON_SECRET}
BACKUP_PASSPHRASE=${BACKUP_PASSPHRASE}
OUT

cat >&2 <<'WARN'

  Generated. Two things to do now, before anything else:

    1. Paste the block above into deploy/env/production.env (it was printed to
       stdout, so `deploy/keygen.sh >> deploy/env/production.env` did it for you).
    2. PRINT BACKUP_PASSPHRASE AND PUT IT IN THE SAFE. Encrypted backups cannot
       be read without it, by anyone, ever.

  SERVICE_ROLE_KEY bypasses row-level security. It belongs in that file and in
  the server's environment — never in a browser, a phone, or a chat message.

WARN
